# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"CU": "00_clickup.ipynb"}

modules = ["CUFile.py"]

doc_url = "https://StevedeP.github.io/CUFT/"

git_url = "https://github.com/StevedeP/CUFT/tree/0/"

def custom_doc_links(name): return None
